# Generated by Django 2.0.13 on 2020-12-06 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lead_Management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup_history',
            name='abc',
        ),
        migrations.AddField(
            model_name='followup_history',
            name='source_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Lead_Management_app.source_list'),
        ),
    ]
